name: 更新数据并部署

on:
  # schedule:
    # Disabled - runs too frequently
    # - cron: '0 */6 * * *'
  # push:
  #   branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v3
        with:
          version: 8.4.0
      - run: pnpm install --frozen-lockfile
      - run: node scripts/update-feeds.js
        env:
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_API_BASE: ${{ secrets.LLM_API_BASE }}
          LLM_NAME: ${{ secrets.LLM_NAME }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_API_KEY_2: ${{ secrets.GEMINI_API_KEY_2 }}
          GEMINI_API_KEY_3: ${{ secrets.GEMINI_API_KEY_3 }}
          GEMINI_API_KEY_4: ${{ secrets.GEMINI_API_KEY_4 }}
          GEMINI_API_KEY_5: ${{ secrets.GEMINI_API_KEY_5 }}
          GEMINI_API_KEY_6: ${{ secrets.GEMINI_API_KEY_6 }}
          GEMINI_API_KEY_7: ${{ secrets.GEMINI_API_KEY_7 }}
          GEMINI_API_KEY_8: ${{ secrets.GEMINI_API_KEY_8 }}
          GEMINI_MODEL_NAME: ${{ secrets.GEMINI_MODEL_NAME }}
      
      # Commit the updated data back to the repository
      - name: Commit updated data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./data/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update RSS feed data [skip ci]"
            git push
          fi
      
      - uses: actions/upload-artifact@v4
        with:
          name: data-artifact
          path: ./data

  deploy-github-pages:
    needs: update-data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v3
        with:
          version: 8.4.0
      - run: pnpm install --frozen-lockfile
      - uses: actions/download-artifact@v4
        with:
          name: data-artifact
          path: ./data
      - name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
      - name: Set environment variables for build
        run: |
          echo "NODE_ENV=production" >> $GITHUB_ENV
          echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV
      - run: pnpm build
        env:
          REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}
          NODE_ENV: ${{ env.NODE_ENV }}
          GITHUB_ACTIONS: ${{ env.GITHUB_ACTIONS }}
      - name: Add .nojekyll to output directory  
        run: touch ./out/.nojekyll

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
      - id: deployment
        uses: actions/deploy-pages@v4

  deploy-vercel:
    needs: update-data
    runs-on: ubuntu-latest
    if: ${{ vars.ENABLE_VERCEL_DEPLOYMENT == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: data-artifact
          path: ./data
      - uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod --build-env VERCEL=1'
